-- MySQL Script generated by MySQL Workbench
-- jeu. 13 juil. 2017 16:40:49 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`organisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organisation` (
  `idorganisation` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `website_url` VARCHAR(45) NULL,
  PRIMARY KEY (`idorganisation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tweet` (
  `idtweet` INT NOT NULL,
  `content` LONGTEXT NULL,
  PRIMARY KEY (`idtweet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `tweet_idtweet1` INT NOT NULL,
  PRIMARY KEY (`iduser`, `tweet_idtweet1`),
  INDEX `fk_user_tweet_idx` (`tweet_idtweet1` ASC),
  CONSTRAINT `fk_user_tweet`
    FOREIGN KEY (`tweet_idtweet1`)
    REFERENCES `mydb`.`tweet` (`idtweet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organisation_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organisation_has_user` (
  `organisation_idorganisation` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `user_tweet_idtweet1` INT NOT NULL,
  PRIMARY KEY (`organisation_idorganisation`, `user_iduser`, `user_tweet_idtweet1`),
  INDEX `fk_organisation_has_user_user1_idx` (`user_iduser` ASC, `user_tweet_idtweet1` ASC),
  INDEX `fk_organisation_has_user_organisation1_idx` (`organisation_idorganisation` ASC),
  CONSTRAINT `fk_organisation_has_user_organisation1`
    FOREIGN KEY (`organisation_idorganisation`)
    REFERENCES `mydb`.`organisation` (`idorganisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organisation_has_user_user1`
    FOREIGN KEY (`user_iduser` , `user_tweet_idtweet1`)
    REFERENCES `mydb`.`user` (`iduser` , `tweet_idtweet1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
